### ISSUE TITLE
Lesson生成发生Error

### ISSUE THREAD

**Issue by woate** [wensiqun/asmsupport#2]
Lesson5.test1发生java.lang.VerifyError: Control flow falls through code end
Lesson4.test4发生java.lang.VerifyError: Control flow falls through code end
Lesson3.test2发生java.lang.VerifyError: Control flow falls through code end

**Comment by wensiqun** [comment]
Fixed, 多数是因为方法体没有调用return或者方法未被指定为public。Lesson4.test4问题参考[https://github.com/wensiqun/asmsupport/issues/3](url)
